# Generated by Django 3.2.25 on 2025-01-03 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_movie_options_remove_movie_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the release year of the movie', null=True, validators=[django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
